spring:
  application:
    name: smart-expense-tacker-api

  datasource:
    url: jdbc:postgresql://ep-sparkling-lab-amc1xv05-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_1NWVOjvAkce6
    driver-class-name: org.postgresql.Driver
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
 
  main:
    # Turns off the Spring ASCII Art
    banner-mode: "off"
    # Optional: Silences startup info logs but keeps errors
    log-startup-info: false

logging:
  level:
    # Root level WARN silences the generic Spring/Hibernate/Tomcat logs
    root: WARN
    # Keep your specific package at INFO so you can see your own logs
    mayur.dev.smartexpensetackerapi : INFO
    # Silences the specific "Bean successfully defined" spam
    org.springframework.web: WARN

